// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmvumzaiigxyficbanjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdnVtemFpaWd4eWZpY2JhbmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTM0ODcsImV4cCI6MjA1NDE4OTQ4N30.8AMcp7uZvyvlN5QfwChsHwyF9qSu-Vfv9kTrjyB5-XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);